utopia-php/database

- composer.lock
- src/Database/Validator/Authorization.php
- src/Database/Validator/DocumentId.php
- src/Database/Validator/Key.php
- src/Database/Validator/Permissions.php
- src/Database/Validator/UID.php
Implementing necessary abstract methods after `utopia-php/framework` validator changes.
> Update validators with new abstract methods

- Dockerfile
- README.md
- composer.json
- composer.lock
- docker-compose.yml
- src/Database/Database.php
- src/Database/Document.php
- tests/Database/Adapter/MariaDBTest.php
This PR allows for the use of a cache when creating a database.
> Feat - Caching layer to database

- src/Database/Database.php
- src/Database/Validator/Query.php
- src/Database/Validator/QueryValidator.php
- tests/Database/Validator/QueryValidatorTest.php
This PR introduces a query validator which checks a query against a collection schema for validity.
> Add query validator

- composer.json
- composer.lock
- src/Database/Query.php
This PR addresses the included psalm warnings by:
- upgrading `utopia-php/cache` to 0.4.1, which appropriately typehints `$cache->save()`
- declare and typehint `Query::parse() where necessary`
Warnings from psalm, for reference:
```
$ docker-compose exec tests vendor/bin/psalm --show-info=true
Scanning files...
Analyzing files...
░░░░░░I░░░░I░░░░░░░░
INFO: InvalidArgument - src/Database/Database.php:488:33 - Argument 2 of Utopia\Cache\Cache::save expects string, array<array-key, mixed> provided (see https://psalm.dev/004)
$this->cache->save($id, $document->getArrayCopy()); // save to cache after fetching from db
INFO: InvalidArgument - src/Database/Database.php:580:48 - Argument 2 of Utopia\Cache\Cache::save expects string, array<array-key, mixed> provided (see https://psalm.dev/004) …
```
> V0 fix psalm warnings

- src/Database/Validator/Queries.php
- tests/Database/Validator/QueriesTest.php
This PR introduces a new Queries validator to validate an array of Query objects by:
- Individually validating each Query object
- **Strict validation**: validate the query params can all be found in one index
- Checks if index is queued for creation during strict validation
Test plan:
Unit tests included
TODO:
> Feature - Strict Query Validation

- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
- src/Database/Database.php
- src/Database/Query.php
- src/Database/Validator/Queries.php
- src/Database/Validator/QueryValidator.php
- tests/Database/Adapter/MariaDBTest.php
- tests/Database/Adapter/MongoDBTest.php
- tests/Database/Adapter/MySQLTest.php
- tests/Database/Base.php
- tests/Database/Validator/QueriesTest.php
- tests/Database/Validator/QueryValidatorTest.php
This PR adds a MongoDB database adapter
> Feat: MongoDB Adapter

- src/Database/Adapter/MariaDB.php
Moving the individual permissions IN query to the WHERE clause (from the JOIN) increases query performance at scale on certain indexes.
Results for 250k documents, limit 25:
| ~500 roles                                           | Before (s)          | After (s)              |
|------------------------------------------------------|-----------------|--------------------|
| text.search('Alice')                                 | 10.322902917862 | 10.365649223328    |
| [created.greater(1262322000), genre.equal('travel')] | 1.6036841869354 | 1.6573619842529    |
| genre.equal('fashion', 'finance', 'sports')          | 1.8061821460724 | 0.0035700798034668* |
| views.greater(100000)                                | 2.4185400009155 | 2.3989799022675    |
| ~1000 roles …
> Refactor - Adjust permissions query for performance

- .gitignore
- Dockerfile
- README.md
- bin/cli.php
- bin/compare
- bin/index
- bin/load
- bin/query
- bin/tasks/index.php
- bin/tasks/load.php
- bin/tasks/query.php
- bin/view/index.php
- composer.json
- composer.lock
- docker-compose.yml
- src/Database/Adapter/MariaDB.php
Three commands have been added to `bin/` to fill, index, and query the DB to test changes:
- `bin/load` invokes `bin/tasks/load.php`
- `bin/index` invokes `bin/tasks/index.php`
- `bin/query` invokes `bin/tasks/query.php`
To test your DB changes under load:
**=> Load the database**
```bash
docker-compose exec tests bin/load --adapter=[adapter] --limit=[limit] [--name=[name]]
```
**=> Create indexes**
```bash
docker-compose exec tests bin/index --adapter=[adapter] --name=[name]
```
**=> Run Query Suite**
```bash
docker-compose exec tests bin/query --adapter=[adapter] --limit=[limit] --name=[name]
```
> Feat - Script to fill databases

- src/Database/Validator/Key.php
- src/Database/Validator/UID.php
- tests/Database/Validator/KeyTest.php
- tests/Database/Validator/UIDTest.php
This PR harmonizes the UID and Key validators. Keys and UIDs must both satisfy the following:
- Must be string
- Must be alphanumeric + underscore "_"
- No leading underscore
- Maximum of 32 chars
**Tests**
Harmonized the tests as well, refactoring the expected value to first `assert` param and restructured for clarity.
> Feat - Harmonize UID with Key validator

- src/Database/Validator/Permissions.php
- tests/Database/Validator/PermissionsTest.php
This PR expands the permissions validator to check the format of the permission strings. Since the removal of the wildcard char `*`, a "role" satisfies the following simple schema:
- Can be expressed in the format `{$type}:{$value}` with only a single colon separating the permission type from its value
- `$type` must be one of `['member', 'role', 'user', 'team']`
- `$value` must not be empty
- `$value` must satisfy the Key validator for `user` and `member`
- `$value` must be one of `['all', 'guest', 'member']` when `$type = 'role'`
- Since `team:[teamId]/[role]` can have any string for role, no validation needed
Unit tests included
> Feat - Expand Permissions validator

- src/Database/Database.php
- tests/Database/Base.php
This PR introduces a default value when creating an attribute. An exception is thrown if the type of default value does not match the type of attribute, as the database would be unaware of the mismatched type until a document is created.
**Testing**
Unit tests have been added to test for valid and invalid default values.
> Feat - Attribute default values

- src/Database/Adapter/MariaDB.php
By default, `PDO->fetch()` is configured to the default mode:
>  PDO::FETCH_BOTH (default): returns an array indexed by both column name and 0-indexed column number as returned in your result set
This causes problems on `getDocument()` calls, as the returned document fails structure validation (with the additional indexed array data in the return structure). This PR changes the default mode in the MariaDB/MySQL adapters to return the assoc array we want.
> Fetch should return only assoc array, not PDO::FETCH_BOTH (default)

- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
- src/Database/Adapter/MySQL.php
- src/Database/Database.php
- tests/Database/Base.php
Creating collections with many attributes (for example, on startup of Appwrite, for testing) can be slow, so this PR adds additional params to `createCollection` to generate a complete collection with one call:
```php
abstract public function createCollection(string $name, array $attributes = [], array $indexes = []): bool;
```
**Testing**
Additional unit tests will be added to validate functionality.
<details>
<summary>Screenshots of index creation from tests</summary>
</details>
> Allow for creation of collection with complete schema

- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
- src/Database/Database.php
- src/Database/Exception/IndexLimit.php
- tests/Database/Base.php
Each database has a maximum number of indexes per collection/table. This PR adds a new exception IndexLimit (not sure on the name), implemented per adapter, so these cases can be appropriately handled.
**Testing**
Additional tests have been added for these conditions.
> Feat - Index limits

- src/Database/Database.php
- tests/Database/Base.php
Appwrite creates indexes asynchronously, so the API calls `addIndexInQueue()` and triggers the Database worker to perform the action. 
To be able to throw/catch `IndexLimitException` meaningfully, this index check should be on both `createIndex` and `addIndexInQueue()`.
> Throw IndexLimit when adding index to queue

- src/Database/Database.php
- tests/Database/Validator/QueriesTest.php
Changed generic key name to `key` instead of `text`
> Fix key name

- src/Database/Adapter/MariaDB.php
- src/Database/Database.php
This PR refactors `Utopia\Database->create()` to utilize a single call to `createCollection()` for the default collection schema. This change is known to be faster at creating tables than creating the attributes/columns one-by-one.
> Refactor - Create collection in single call

- src/Database/Database.php
- tests/Database/Base.php
`Utopia\Database\Database->findFirst()` is primarily used to find a single document, and `findLast()` isn't used at all. 
This PR renames `findFirst` to `findOne` (similar to [mongo](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-findOne/)) and removes `findLast`.
> Refactor findFirst to findOne

- src/Database/Validator/Key.php
- src/Database/Validator/UID.php
- tests/Database/Validator/KeyTest.php
- tests/Database/Validator/PermissionsTest.php
This PR increases the supported length for Keys and UIDs from 32 chars to 36 chars. With this change, we can support `uuidv4` as valid UIDs.
**Testing**
Tests have been updated to reflect this change
> Accept 36 chars as keys

- src/Database/Database.php
- src/Database/Validator/Structure.php
- tests/Database/Base.php
- tests/Database/Validator/StructureTest.php
Most of the required logic for custom validation was [already in place](https://github.com/utopia-php/database/blob/main/src/Database/Validator/Structure.php#L258-L280) in the structure validator, but it was not being used in the Database class.
This PR:
1. Adds a param when creating attributes to store any custom validation on the attribute:
```php
/**
@param string $format JSON-encoded string of format metadata. Key 'name' required.
*/
```
2. Updates the logic for `Structure::addFormat` to accept a callback which creates a validator based on attribute structure. 
3. Throws an exception on `createAttribute` methods when a format is unknown.
The custom validator name is stored as the $format param for attribute creation and is used to use the correct validator for document structure. This …
> Accept array of formats for custom structure validation

- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
- src/Database/Database.php
The previous logic properly throws `LimitException` on both `createIndex` and `addIndexInQueue` methods, when handled as separate methods. However, when implementing in Appwrite, the error must be properly thrown from `addIndexInQueue` since the Database worker, not `appwrite` itself, calls `createIndex`. 
This PR: 
1. changes the location in code where we check the limit, but no functionality has changed. Note the sign change from `>=` to `>` with the refactored logic.
2. Limit checking methods now accept a `$strict` parameter to only count columns/indexes on table and not in queue. 
**Testing**
- Existing unit tests cover proper exception handling.
> Check index limit after appending to index queue

- docker-compose.yml
- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
- src/Database/Database.php
- src/Database/Document.php
- src/Database/Query.php
- src/Database/Validator/Structure.php
- tests/Database/Adapter/MariaDBTest.php
- tests/Database/Adapter/MongoDBTest.php
- tests/Database/Adapter/MySQLTest.php
- tests/Database/Base.php
- tests/Database/Validator/StructureTest.php
- allow queries to paginate after a specific document
- for MariaDB, we are using the internal `_id` as a subsequent value to query after a certain document while allowing to sort
- since we need the internal `_id` and every attribute and its proper datatype, a document need to be passed instead of only its Document ID
References can be found here: https://shopify.engineering/pagination-relative-cursors
For MongoDB we are using the same approach, except that we are using the native `_id` as a subsequent value.
> feat(find): after document pagination

- src/Database/Database.php
- tests/Database/Base.php
The `Utopia\Database\Database->create()` method created a unique index on collection names. This index has been removed, as the `uniqid` should be the only unique column.
Unanswered questions:
> Fix: remove unique index from collection name

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
- tests/Database/Base.php
- allows to order by `ASC` or `DESC` without specifying any `orderAttributes`
- this will fallback to the natural order by `_id`
> feat(order-type): allow order type with natural order

- src/Database/Validator/Key.php
- tests/Database/Base.php
- tests/Database/Validator/KeyTest.php
- tests/Database/Validator/PermissionsTest.php
This PR adds support for additional special characters for keys: periods, spaces, and hyphens. As custom attributes, however, MariaDB brings the following restriction:
> Database, table and column names can't end with space characters
> ref: https://mariadb.com/kb/en/identifier-names/#further-rules
This PR adds the extra characters to the Key validator (which UID inherits) and adds both unit tests and as attributes on each database adapter. 
The regex changes just add the additional characters as valid:
https://github.com/utopia-php/database/blob/1f6ce90e2649b874a662bdf8c0cd0cb5b0ce836b/src/Database/Validator/Key.php#L52-L55
> Accept periods, spaces, and hyphens as keys

- src/Database/Database.php
- tests/Database/Base.php
Problem:
- when a collection get created, the cache only had the version without an internal ID present
Solution:
- only save a document into cache on `updateDocument` when an internal ID is present
> fix(cache): don't save document into cache on update

- src/Database/Database.php
- src/Database/Validator/Authorization.php
- tests/Database/Validator/AuthorizationTest.php
The Authorization validator required a `Utopia\Database\Document` object but isn't used during validation. This PR removes the document from the constructor.
**Testing**
Test suite has been updated to reflect this change.
> Removed unused document from Authorization constructor

- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
In https://github.com/utopia-php/database/pull/46, we refactored the default index count into a public static method for clarity and maintainability. However, I overlooked in my review that we don't have a 1-1 for default attributes&indexes - we don't index **$write** permissions since they aren't used in any of our queries. 
This PR:
- Removes the default index on `_write` in the MongoDB adapter
- Adds an additional method `getNumberOfDefaultAttributes()` to adapters.
**Testing**
Current test suite is sufficient to cover this change.
> Fix default attribute index count

- src/Database/Adapter/MongoDB.php
- src/Database/Database.php
- tests/Database/Base.php
MongoDB document keys are [case sensitive](https://docs.mongodb.com/manual/core/document/#field-names), but MariaDB column names [are not](https://mariadb.com/kb/en/identifier-case-sensitivity/).
This PR adds a case-insensitive check when creating attributes/indexes or adding one to the queue, and will throw `Utopia\Database\Exception\Duplicate` if a match is found. 
This PR also changes the default index on `_uid` for the MongoDB adapter to be case-insensitive.
**Testing**
Tests have been added to catch these exceptions.
**Unanswered questions**
> Throw exception on case-insensitive duplicate IDs

- src/Database/Validator/Key.php
- tests/Database/Validator/KeyTest.php
- tests/Database/Validator/PermissionsTest.php
This PR changes the Key validator to no longer accept leading hyphens and periods as valid.
**Testing**:
The test suite has been updated to reflect this change.
> Disallow leading special characters for Keys

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
- tests/Database/Base.php
This PR catches the exception thrown when a collection enforces a unique index, and a document is updated to conflict with an existing document in the collection.
**Testing**:
Tests have been added to catch this exception properly.
> Throw correct error when updating documents with unique index

- src/Database/Validator/Queries.php
- tests/Database/Validator/QueriesTest.php
This PR refactors the Queries validator constructor method to accept array of documents:
```diff
- @var array $indexes
+ @var Document[] $indexes
- @var array $indexesInQueue
+ @var Document[] $indexesInQueue
```
This improves the DX when consuming in Appwrite, as the construction of Queries validator becomes simpler:
```php
$validator = new Queries($queryValidator, $collection->getAttribute('indexes'), $collection->getAttribute('indexesInQueue'));
```
**Testing**:
The current test suite should cover this modification.
> Accept array of index documents when constructing Queries validator

- src/Database/Database.php
The new format allows a better UI presentation and better cleaning capabilities using specific patterns. For example:
> Updated cache keys for better Redis UI expirience

- tests/Database/Base.php
This PR adds a test to check the case-insensitive index on `$id` across all adapters.
**Related PRs**
https://github.com/utopia-php/database/pull/49
**Testing**
Tests are included in this PR
> Add test for case insensitive documentID

- src/Database/Database.php
In https://github.com/utopia-php/database/pull/64, we added the ability to pass the document when encoding an attribute:
https://github.com/utopia-php/database/blob/7c26cb324ccefb047f06733f59871c937dba4cb9/src/Database/Database.php#L1093-L1105
This PR extends that functionality to encodeAttribute so we can manipulate the document when trying to encode into a database format.
> Pass document and database to encodeAttribute to mirror decodeAttribute

- src/Database/Database.php
- tests/Database/Base.php
If attribute creation/deletion are performed entirely asynchronously, then there's no way to throw an in-memory exception for attribute limits. This PR creates a method which checks for attribute limits without modifying the original `Document $collection` object.
**Testing**
This PR includes tests for each exception the new method throws.
**Questions**
> Add checkAttribute method

- src/Database/Database.php
- tests/Database/Adapter/MariaDBTest.php
- tests/Database/Adapter/MongoDBTest.php
- tests/Database/Base.php
This PR introduces two methods for easy checks of database limits to keep to a DRY approach:
- `getAttributeLimit()`
- `getIndexLimit()`
**Testing**
Tests have been added for the new methods, and the test suite has been updated to utilize them.
**Dependencies**
Forked from https://github.com/utopia-php/database/pull/72. Will convert from draft when parent branch merged.
> feat: get limit methods on database

- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
- src/Database/Database.php
- tests/Database/Base.php
Adds the ability to paginate `before` an id.
Technically, it will be done the way `after` is paginated - just that the ordering is reversed and after we fetched the results we invert the array. Sadly there is no easy implementation, since negative offsets are not a thing.
Source: https://medium.com/swlh/how-to-implement-cursor-pagination-like-a-pro-513140b65f32
Breaking changes:
- renames `orderAfter` to `cursor`
- adds `cursorDirection` with `after` by default
> feat(query): before pagination

- src/Database/Database.php
- src/Database/Validator/Structure.php
- tests/Database/Validator/StructureTest.php
Edge cases around validating arrays kept popping up, so I've cleaned up the logic of the Structure validator, and that covered all cases where the incorrect validator was applied. This change was required because array attributes were validated with the wrong validator. Additionally, this change accepts empty arrays as well as null for optional array attributes.
Additional unit tests have been added to Structure tests to check these cases.
optional URL array attribute is required
> Feat: allow null and empty arrays for optional array attributes

- src/Database/Query.php
- tests/Database/QueryTest.php
This PR adds a convenience method to the Query class that checks against the list of defined query operators. 
**Testing**
Unit tests were added to validate the method's behavior
> Feat: add helper method to check query operators

- src/Database/Validator/QueryValidator.php
- tests/Database/Validator/QueriesTest.php
- tests/Database/Validator/QueryValidatorTest.php
This PR updates the constructor of the Query Validator to accept an array of Utopia\Database\Document objects. This change was made to harmonize with the Queries validator, which depends on this class.
**Testing**
Affected tests have been updated
> Construct query validator from array of attribute documents

- src/Database/Adapter/MariaDB.php
- tests/Database/Base.php
Closes #83
The SQL syntax was different between queries calling `find` vs `count` - the WHERE conditions weren't getting surrounding parentheses for OR statements, leading to inconsistent results between the two methods. 
Testing:
Tests have been added to both methods to ensure this behavior stays in tact.
> Fix: statements with OR clauses when counting documents

- src/Database/Database.php
- tests/Database/Base.php
`uniqid()` generates IDs based on current timestamp, and we've hit collisions in the Appwrite Database API when adding a bunch of documents in sequence. Increasing the entropy was decent idea, but I think the period delimiter will cause more troubles than problems it would solve:
```
mysql> select _uid from documents;
+-------------------------+
| _uid                    |
+-------------------------+
| 619bff85daece7.47129785 |
| 619bff85dd7828.93935232 |
| 619bff85dfdb23.11230448 |
| caseSensitive           |
| duplicated              |
+-------------------------+
5 rows in set (0.00 sec)
```
`random_bytes()` serves as a good replacement with better controls, but we lose the safety that time-based randomIDs provide against collision. This PR adds a $padding parameter to getId to avoid …
> Feat: pad uniqid with random bytes

- src/Database/Database.php
- tests/Database/Base.php
So we don't have to update every `$database->getId()` in Appwrite, this PR sets a default padding of 7 extra chars, leading to a 20-char unique ID, 13 chars based on time, 7 random. 
This should prevent most instances of collision across systems in tandem with unique indexes in the database.
> Fix: default to 20-char uniqids

- composer.lock
- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
- src/Database/Adapter/MySQL.php
- src/Database/Database.php
- src/Database/Validator/Key.php
- tests/Database/Adapter/MariaDBTest.php
- tests/Database/Adapter/MongoDBTest.php
- tests/Database/Adapter/MySQLTest.php
- tests/Database/Base.php
In order to more easily integrate with existing production setups, Appwrite is moving to contain everything under one database. To do this, the database library required two major changes:
- Supporting a default database where everything will be created
- Prepend namespace to table/collection names
This PR introduces the concept of a "default database" that many DBMS support, synonymous to the `USE` SQL instruction.
**HIDDEN GAINS**
I feel more confident that database/collection names are properly escaped in queries, so we may not need to be afraid to support special ASCII characters as names. These changes were made in both the SQL and Mongo adapters.
**TESTING**
Only small changes to `createExistsDelete` tests were required, rest of suite remains unchanged.
> Feat: namespace as table prefixes

- src/Database/Adapter/MariaDB.php
- tests/Database/Base.php
This PR adds support for BIGINT values, triggered when integer is created with `$size >= 8`. MongoDB shouldn't require any modifications, since it should transparently detect the `LONG` BSON type automatically.
Tests:
Tests have been added to check BIGINT/LONG support.
Related issues:
https://github.com/utopia-php/database/issues/94
Have you read the contribution guide?
Yes.
Refs:
https://mariadb.com/kb/en/bigint/
https://mariadb.com/kb/en/int/
https://mariadb.com/kb/en/data-type-storage-requirements/
https://docs.mongodb.com/manual/reference/bson-types/#bson-types
> Feat: support BIGINT/LONG type

- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
- src/Database/Database.php
- tests/Database/Base.php
Since moving every collection to a single default database, we lose the ability to know if a collection has been properly configured (e.g. does the metadata table exist). 
This PR extends `Utopia\Database\Database::exists()` to optionally accept a collection name and test for its existence. 
**Notes**
I'm not sold on this, but the only other nice name I could come up with was `collectionExists()` which doesn't fit the pattern. Alternative suggestions welcome.
**Testing**
Unit tests have been added for both success and failure.
> Feat: check if collection exists in database

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MySQL.php
- tests/Database/Base.php
Before, attempt to create index with id `order` would fail:
```
CREATE INDEX order ON `appwrite`.`_project_dev_collection_posts` ( `title`(255) ASC );
```
```
appwrite-worker-database        | SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order ON `appwrite`.`_project_dev_collection_posts` ( `title`(255) ASC )' at line 1
```
With this PR, `order` is a valid ID of the key.
> Escape index id properly

- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
- src/Database/Adapter/MySQL.php
- src/Database/Database.php
- src/Database/Query.php
- tests/Database/Base.php
With this PR, every Collection will have a dedicated table with all its row level permissions.
The table has 4 columns:
- `_id` internal id (auto incremented)
- `_type` either `read` or `write` (possibility to extend in the future)
- `_permission` the actual permission value
- `_document` reference to the `_uid` for the document
Now that the Permissions are not saved within the actual row of a document anymore, we need to aggregate those informations. For this I am utilizing the [JSON_ARRAYAGG](https://mariadb.com/kb/en/json_arrayagg/) function, which will automatically get all permissions for a Document and outputs it as a JSON array string.
In terms of performance there is very little to no impact and it also allows us to have data integrity over saving the permissions additionally with …
> feat: dedicated permissions table

- src/Database/Adapter/MariaDB.php
- tests/Database/Base.php
- trailing wildcard search by default
- wrap search condition in `"` to prevent SQL errors
> fix: trailing wildcard search by default

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MongoDB.php
- tests/Database/Base.php
Before, people were not able to sort by `$id`, saying `attribute 'id' not found`. Now, people can use `$id` and it is translated to `_uid` under the hood, similar to `queries` with `$id`.
> Added $id support for sortAttribute

- src/Database/Validator/Structure.php
- tests/Database/Validator/StructureTest.php
Size limit is now properly applied on string arrays:
> Fix: array string validator

- composer.lock
- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Database.php
- tests/Database/Base.php
New methods (for migration use, as of right now):
- updateAttributeRequired
- updateAttributeFormat
- updateAttributeFormatOptions
- updateAttributeFormatFilters
- updateAttributeDefault
- updateAttribute (to update size&type&signed&array)
The new private method introduced to prevent code duplication:
- updateAttributeMeta
TODO:
> Feat: Add update attribute methods

- README.md
- src/Database/Adapter/MariaDB.php
- src/Database/Database.php
- src/Database/Document.php
- src/Database/Validator/Structure.php
- tests/Database/Base.php
- Adding 2 new attributes to all collections _createdAt, _updatedAt.
- Readme.md changes adding default setting ATTR_EMULATE_PREPARES, ATTR_STRINGIFY_FETCHES, which are default .
- Removing MYSQL_ATTR_INIT_COMMAND (charset=utf8mb4) , which is set on new PDO.
- Removing PDO::FETCH_ASSOC on each query , which is set globally on connection.
- On CREATE TABLE remove "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4" which are set on default database instance creation.
> Creating UpdatedAt and CreatedAt attributes for collections.

- src/Database/Adapter/MariaDB.php
- src/Database/Document.php
- tests/Database/Base.php
Currently if you pass duplicate permission to `updateDocument` you will get `Error: Document already exists`
```js
const read = ["user:abc", "user:cde", "user:abc"];
updateDocument("collection","documentId", { key: "value"}, read); // Error: Document already exists
```
This is because [this lines](https://github.com/utopia-php/database/blob/main/src/Database/Adapter/MariaDB.php#L594-L601) doesn't remove the duplicate items:
```js
$readAdded = array_diff($document->getRead(), $permissions['read']);
$writeAdded = array_diff($document->getWrite(), $permissions['write']);
```
I have used `array_unique` in `getRead` and `getWrite` as this way we make sure we always get unique permission when we request permissions
> Fix avoid duplicate permissions

- src/Database/Validator/Permissions.php
- tests/Database/Validator/PermissionsTest.php
In Appwrite we recently introduced the default maximum length for each array input which is 100 elements. With this change, we add support for this new feature into permissions validator.
> Feat: Permissions validator max-length

- src/Database/Adapter/MariaDB.php
- tests/Database/Base.php
We previously had a PR addressing this for $id: https://github.com/utopia-php/database/pull/140
This PR addresses the same edge case, but for createdAt+updatedAt.
Issue: https://github.com/appwrite/appwrite/issues/3403
> Fix: Date ordering with Cursor

- tests/Database/Base.php
Adds a missing test for `notEqual()`
> Feat: Add notEqual test

- src/Database/Validator/Queries.php
- src/Database/Validator/QueryValidator.php
- tests/Database/Validator/QueriesTest.php
Ignores query order for validation.
These Queries are Allowed:
- A,B,C
- A,C,B
- B,A,C
- B,C,A
- C,A,B
- C,B,A
Previous implementation only allowed following Queries:
- A,B,C
This will make Indexes more accessible 👍🏻
> feat: index validation without order

- src/Database/Database.php
- src/Database/Permission.php
- tests/Database/Base.php
- tests/Database/Validator/AuthorizationTest.php
- Revert permissions checks to check document level
- **Remove authorisation check for document create**
- Implement aggregate functionality permission helper
We have verified that the removal of the authorisation check in `createDocument` should not have an impact in Appwrite, as all resource types that are publicly creatable, already have the necessary checks in place to ensure they can not be abused.
> Refactor permissions

- composer.lock
- src/Database/Database.php
- tests/Database/Base.php
Currently if you want to deletDocument() or updateDocument(), you need read permission. That is not expected behaviour. 
This PR addresses that.
> Fix: delete/update to not require read permission

- composer.lock
- src/Database/Database.php
- src/Database/Permission.php
- src/Database/Role.php
- src/Database/Validator/Authorization.php
- src/Database/Validator/Permissions.php
- src/Database/Validator/Roles.php
- tests/Database/PermissionHelperTest.php
- tests/Database/RoleHelperTest.php
- tests/Database/Validator/PermissionsTest.php
- Remove regex matching permissions/roles
- Return specific error messages for invalid permissions/roles
- Improve permissions/roles string parsing
- Make status a dimension instead of role for consistency
- `status:verified`-> `users/verified` 
- Add optional status param to `user` and `users` role helpers
- Remove all legacy roles to avoid future migrations
> Refactor permissions valdiators

- src/Database/Database.php
Currently we do this filtering of queries in before running count() method in Appwrite. Problem is, we have a lot of duplicate code because of that. Also there is no reason why you would need non-filter (order, for example) queries when counting.
Addresses: https://github.com/appwrite/appwrite/pull/3702#discussion_r958287285
> Fix: Improve count

- src/Database/Adapter/MariaDB.php
Rename indexes from general like `_index1` to more descriptive names such as `_uid`.
> Feat: Properly name ID indexes

- src/Database/Database.php
This method is called from inside `create()` and is no longer needed as a standalone method.
> Deprecate metadata method

- src/Database/Database.php
- tests/Database/Base.php
- Introduces events and listeners on the database functions
- Each function will generate relevant events
- All event constants are added in the Database class
- Relevant tests added in the base test
- Revert `metadata` back to `_metadata`
> add event, triggers and listeners support

- src/Database/Database.php
- When throwing filter not found exception, give the name of the filter that was not found
> give the filter name that was not found

- src/Database/Validator/Query.php
- tests/Database/Validator/QueryTest.php
Currently you can not query a float attribute with an integer value, but you can set one. This PR allows you to pass an integer or float value in a query
Fixes https://github.com/appwrite/appwrite/issues/4340
> Allow querying float attribute with integer values

- src/Database/Validator/Structure.php
When creating a document, no error is thrown if you pass 0 to the optional array field. This PR fixes that issue.
Closes https://github.com/appwrite/appwrite/issues/5013
> Fixed No Error when Creating a Document with value 0 for array attribute

- composer.json
- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Mongo.php
- src/Database/Adapter/Postgres.php
- src/Database/Adapter/SQL.php
- src/Database/Query.php
- tests/Database/Base.php
- tests/Database/QueryTest.php
- tests/Database/Validator/QueryTest.php
- Added startsWith and endsWith query operators that match the start or end of a string. 
- Uses the `LIKE` operator for SQL
- Uses the `$regex` opearator for Mongo.
Added new tests
> Add `startsWith` and `endsWith` operator

- src/Database/Adapter/SQL.php
- Fix type for `bindConditionValue` method to allow `PDOStatementProxy` as well as `PDOStatement` for Swoole support
> Fix swoole type hint for bind value

- src/Database/Database.php
- src/Database/Exception/Conflict.php
- tests/Database/Base.php
The timestamp property is then used to provide context for
when the request was initially made so that a Conflict
exception can be thrown if a Document was updated or
deleted after the initial request timestamp.
There were 3 options in how to add this timestamp:
1. Add the timestamp to the updateDocument() function
2. Add setTimestamp() and resetTimestamp()
3. Add a withRequestTimestamp() function
The problem with option 1 is that it would pollute the signature and
make it messy.
The problem with option 2 is it adds a global state that developers
would need to make sure to reset. Not doing so can lead to unexpected
behavior.
Option 3 will require modifying places were we want to use the request
timestamp, but this explicitness is best for maintainability.
> Update Database to have a timestamp property

- src/Database/Database.php
The default visibility is public, but we should be consistently explicit.
> Fix Database->withRequestTimestamp() to make it public

- composer.lock
- src/Database/Query.php
- tests/Database/QueryTest.php
- tests/Database/Validator/QueryTest.php
Between query parser supported syntax `between("age", [15, 18])`. Now it supports `between("age", 15, 18)`
> Fix: Between query

- phpunit.xml
- src/Database/Database.php
- src/Database/Validator/Authorization.php
- tests/Database/Base.php
- implements `documentSecurity` to collections
- respect `documentSecurity` on all CRUD operations
> feat: collection level permissions

- src/Database/Database.php
- tests/Database/Base.php
Before this, if a document had a 1 to 1, parent-sided many-to-one, or child-sided one-to-many relationship, the nested document's ID would still be included in the result even if the user didn't have access to the nested document. This clears the attribute so that the document ID is excluded from the result.
This PR depends on:
* https://github.com/utopia-php/database/pull/262
We should merge the dependant to main and then change this one to merge to main.
> Don't exceed max depth for relationships

- src/Database/Database.php
- tests/Database/Base.php
To do this, we need 1 stack instead of 2 depth counts because:
1. 2 counts won't work when a top level updateDocument() calls createDocument() or vice versa for a nested relationship.
2. A stack will allow us to keep count, but also keep track of the last collection ID so that when we're at the max depth, we only create/update the relationship of the document above rather than continuing deeper.
> Prevent documents nested past the max depth from being created

- src/Database/Database.php
- tests/Database/Base.php
- Fix cascade deletes not accounting for nested relationships
- Added test to check multi-level cascade is working
> Fix cascading deletes across multiple levels

- composer.lock
- phpunit.xml
- src/Database/Database.php
- tests/Database/Base.php
This issue was asked during office hours, Trying to create two relations on the same collection.
So now officially we can...
> Identical twoWayKey

- src/Database/Document.php
- src/Database/Helpers/Permission.php
- tests/Database/PermissionTest.php
- tests/Database/Validator/PermissionsTest.php
Fixes [#5661](https://github.com/appwrite/appwrite/issues/5661)
Unit and E2E testing
> Fix: $permissions returns as object rather than array

- composer.lock
- src/Database/Database.php
- tests/Database/Base.php
When using the find method, while the collection does not exist, we still reach the adapter, sending out a misleading message:
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'utopiaTests.myapp_648844bc2bd08_' doesn't exist
Without the name of the wrong collection.
> Collection not found

- src/Database/Document.php
- tests/Database/DocumentTest.php
This makes it easier and quicker to update several attributes on a document from a different document.
> Add method to Document to set multiple attributes

- src/Database/Helpers/Role.php
- src/Database/Validator/Label.php
- src/Database/Validator/Roles.php
- tests/Database/Base.php
- tests/Database/PermissionTest.php
- tests/Database/RoleTest.php
- tests/Database/Validator/LabelTest.php
- tests/Database/Validator/PermissionsTest.php
- tests/Database/Validator/RolesTest.php
A user can be given a particular label and access to resources can be restricted to only users with that label.
> Add support for label permissions

- src/Database/Database.php
- tests/Database/Base.php
Sometimes you don't want certain database listeners to execute.
> Expose a way to skip specific database listeners

- src/Database/Database.php
- tests/Database/Base.php
We should not throw authorization exception when there is no change in update document coming document.
This is required for Relationships as we need to allow users to update document having related collection with no permission.
Part fix https://github.com/appwrite/appwrite/issues/5404
> No Exception when no change in update document function

- src/Database/Database.php
- tests/Database/Base.php
Previously the comparison check between old document and new document in updateDocument was not able to check if the key is a relationship key or not so it was creating issues when updating document with relationships.
Added test case
> fix comparison check in updateDocument

- src/Database/Database.php
Metadata tables for indexes and attributes does not have key property so select queries cannot be validated. We need to fallback on  when key property is not present in such cases. This commit fixes that. 
Here's a discussion with Jake on this 
https://github.com/appwrite/appwrite/pull/5885#discussion_r1282509448
> Fallback to $id  when validating select queries

- src/Database/Database.php
- tests/Database/Base.php
This PR fixes bug in multiple relationships 
- One to One One way
- One to One Two way (Bug was not reproducible but for consistency added code as well)
- One to Many One Way and Two way
- Many to One one way and two way 
- Many to many one way and two way
Fixes https://github.com/appwrite/appwrite/issues/5871
Previously we were getting 500 for one to one two way as the non existing doc needs to be updated in One to One two-way relationship type and non existing doc does not have key.
Now we are keeping it consistent with other relationship types and skipping non existing doc
> Fix 5871 relationships with non existing documents

- composer.lock
- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/MySQL.php
- src/Database/Adapter/Postgres.php
- src/Database/Database.php
- tests/Database/Base.php
This PR renames multiple functions
-  SetTimeout => SetTimeoutForQuery
- SetTimeoutForAllQueries => SetTimeout
- ClearTimeoutForAllQueries => ClearTimeout
> rename setTimeout methods

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Mongo.php
- src/Database/Adapter/Postgres.php
- src/Database/Adapter/SQL.php
- src/Database/Database.php
- src/Database/Validator/Query/Select.php
- tests/Database/Base.php
@abnegate @fogelito This is the new PR for https://github.com/appwrite/appwrite/issues/5376.
1. Internal attributes are selected if queried inside the `getAttributeProjection` method.
2. Before the document is returned internal attributes which are not queried are removed.
3. Added tests for `getDocument`, `find` and `findOne` method. 
All tests work fine (local machine).
> Improve Select Query

- src/Database/Database.php
- src/Database/Document.php
- tests/Database/Adapter/MariaDBTest.php
- tests/Database/Adapter/MongoDBTest.php
- tests/Database/Adapter/MySQLTest.php
- tests/Database/Adapter/PostgresTest.php
- tests/Database/Adapter/SQLiteTest.php
- tests/Database/Base.php
Now that select queries do not automatically select internal attributes, a call to `$document->isEmpty()` will return true if using a select query and `$id` was not selected. 
This PR changes the empty check to check if the document has _any_ values set instead of only checking if `$id` is set.
> Fix `isEmpty` returning true if $id is not selected

- src/Database/Database.php
- tests/Database/Base.php
This PR checks the nested docs id to the old doc nested docs. 
For example:
If document A is related to document B but we do not have permission to access it, we can still establish a relationship between document A and a different version of document B (let's call it B1). This is because we compare B to its previous version, and B1 to its previous version as well. If there are no changes in B1, then we do not need permission to relate it to document A.
> add checking of nested docs id in comparison check when updating document

- src/Database/Database.php
- tests/Database/Base.php
This PR fixes the edge case of comparing nested doc ID only if the nested level is less than MAX DEPTH allowed.
> fixes edge case in comparison check

- src/Database/Database.php
- tests/Database/Base.php
Previously with partial updates we were not merging missing keys which was causing weird problems like createdAt and updatedAt being null. 
This PR fixes that
> Add test for invalid keys

- src/Database/Database.php
- tests/Database/Base.php
- Skipping authorization for crud operations which are integral parts of logic but not done by the user
- Added a test case.
> Fix crud operations permission in update relationships

- src/Database/Query.php
E.g. Currently:
```php
$queries = [Query::equal('$id', ['123']];
$filters = Query::groupByType()['filters'];
// Changing the attribute of the query in the original array
$queries[0]->setAttribute('_uid');
// Will change the attribute of the query returned by the `groupByType` method, which is unexpected
$filters[0]->getAttribute() === '_uid'
```
This is an issue from Appwrite because we mutate query attributes in the `find` function and then pass the same query references to the `count` function, which means the values are already mutated. Cloning the queries fixes the issue because changes to one array will not affect the other.
> Clone queries when grouping/getting by type so that mutations are not made across references

- composer.json
- src/Database/Adapter.php
- src/Database/Database.php
- src/Database/Exception/Query.php
- src/Database/Query.php
- Fix throwing global exception instead of database exception in some cases
- Add query exception so that query specific exceptions can be caught since validation happens in the library now
> Fix throwing global exception instead of database exception

- src/Database/Database.php
- tests/Database/Base.php
This PR fixes the missing keys when updating doc via relationship. 
We currently delete related keys if the old value is the same as the new value for nested documents. However, this creates a problem when populating relationships. We need the key to have the ID of the related document so that we can fetch it and populate it once the document update process is complete.
> fixes missing keys when updating doc

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Mongo.php
- src/Database/Adapter/Postgres.php
- src/Database/Validator/Queries/Documents.php
- tests/Database/Base.php
- Allow querying on $internalId
Test added
> Allow querying on $internalId

- src/Database/Adapter/SQL.php
- src/Database/Validator/Index.php
- tests/Database/Validator/IndexTest.php
Fix error on Appwrite
Warning: Undefined array key "releaseYear" in /usr/src/code/vendor/utopia-php/database/src/Database/Validator/Index.php on line 114
[Job] (651d3ab6498be6.70825282) failed to run.
[Job] (651d3ab6498be6.70825282) Call to a member function getAttribute() on null
[Error] Type: Error
[Error] Message: Call to a member function getAttribute() on null
[Error] File: /usr/src/code/vendor/utopia-php/database/src/Database/Validator/Index.php
[Error] Line: 116
> Index validation no attibute

- src/Database/Database.php
- src/Database/Validator/Index.php
- tests/Database/Base.php
- tests/Database/Validator/IndexTest.php
Make index validator accept the related collection `attributes` in constructor, and the index document in the `isValid` function. This is more consistent with other validators and allows us to validate a single index at a time instead of the entire collection.
> Fix index validation

- composer.lock
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Postgres.php
- src/Database/Adapter/SQL.php
- src/Database/Adapter/SQLite.php
- src/Database/Validator/Index.php
Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.
> fetchAll getDocument

- Dockerfile
This cuts the size of the layer (and image) by about 250MB.
> Remove postgresql-dev since it's not needed after pdo_pgsql is installed

- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Postgres.php
- src/Database/Adapter/SQLite.php
- src/Database/Database.php
- tests/Database/Base.php
- Allow transforming queries per event
- Add method to set metadata on the database which will be added to queries as comments
> Feat query metadata

- composer.lock
- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Mongo.php
- src/Database/Adapter/MySQL.php
- src/Database/Adapter/Postgres.php
- src/Database/Database.php
- tests/Database/Base.php
Allow using instance level query hooks to set timeout per database event (or all)
Existing tests, updated timeout test
> Global timeouts using before query hooks

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/SQLite.php
Small patch to help fix and resolve deadlocks.
> Protect against deadlocks 

- composer.lock
- src/Database/Database.php
- required to create proxy database from existing database instance
> Changes required for ZDT migration

- src/Database/Adapter/Postgres.php
- src/Database/Database.php
- tests/Database/Base.php
- calling `Authorization::reset()` resets outside usage of `Authorization` class
> fix: remove authorization skip from `listCollections`

- src/Database/Database.php
Allows falsy checks such as 
```php
$doc = $database->findOne(...)
if (!$doc) {
return;
}
// now $doc is type Document
```
> feat: constrain findOne return type

- phpunit.xml
- src/Database/Database.php
- tests/Database/Base.php
Fix Delets Documents with relations when Database::RELATION_MUTATE_SET_NULL and Two-way attribute key value is set to null.
@stnguyen90 We saw this error on Sentry not sure if it is associated with an issue
> Fix getId() on null delete document relations

- src/Database/Validator/Queries.php
There are some scenarios where we need both length and queries validation.
> Add check for length in Queries Validator

- src/Database/Database.php
- src/Database/Exception/Validation.php
- src/Database/Validator/Authorization.php
- tests/Database/Validator/AuthorizationTest.php
Attempt to remove setAction, to prevent bleed of error messages between validation calls
> Fix: setAction method

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Postgres.php
- src/Database/Database.php
- tests/e2e/Adapter/Base.php
Fixes: https://github.com/appwrite/appwrite/issues/6012
> Fix Delete Collection with relations

- composer.lock
- src/Database/Database.php
- tests/Database/Base.php
In some scenarios (migration) you want to create/update a document, but don't want the $createdAt or $updatedAt to change.
I added a parameter to allow control of this. Default stays the same as it is, to prevent breaking changes.
> Feat: preserve dates

- composer.lock
- phpunit.xml
- src/Database/Database.php
- src/Database/Validator/Structure.php
- tests/e2e/Adapter/Base.php
- tests/unit/Validator/StructureTest.php
Structure validator for checking value ranges Numeric attributes
> Integer validator

- src/Database/Adapter/MariaDB.php
In migrations we have an issue where previous tables did not have the _tenant column so trying to insert a new row with this column set would throw an exception. We didn't add this check before to reduce complexity. Now we check all cases where _tenant is used and only add it if `shareTables` is enabled
> Only add tenant attribute when shared tables enabled to fix migrations

- src/Database/Validator/Structure.php
- tests/Database/Validator/StructureTest.php
By validating that all keys of array attributes are numerical and in order from 0..count(values)-1
> Fix structure validator allowing objects for arrays

- src/Database/Database.php
- tests/e2e/Adapter/Base.php
Fix error array_filter(): Argument #1 ($array) must be of type array, null given;
Looks ok just tests for now
> Delete Update not found collection

- src/Database/Validator/Datetime.php
- tests/e2e/Adapter/Base.php
Fix this error
SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value
> fix datetime validation 

- src/Database/Database.php
- tests/e2e/Adapter/Base.php
skipValidation() ensures the initial state will be restored after the callback is executed.
> Add skipValidation method to Database class

- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Mongo.php
- src/Database/Adapter/MySQL.php
- src/Database/Adapter/Postgres.php
- src/Database/Adapter/SQL.php
- src/Database/Adapter/SQLite.php
- src/Database/Database.php
- tests/e2e/Adapter/Base.php
To allow multiple metadata entries to be updated. Temporary fix until all databases are using shared tables with a single metadata document for all projects.
> Don't throw on duplicate column for shared tables

- Dockerfile
- composer.lock
- dev/xdebug.ini
- docker-compose.yml
- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Mongo.php
- src/Database/Adapter/Postgres.php
- src/Database/Adapter/SQLite.php
- src/Database/Database.php
- tests/e2e/Adapter/Base.php
This PR implements the ability to update attribute's names by adding $newKey to `updateAttributes()`; It also includes `xdebug` for easier debugging.
> Implement Renaming Attributes

- composer.json
- composer.lock
- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Mongo.php
- src/Database/Adapter/Postgres.php
- src/Database/Adapter/SQL.php
- src/Database/Adapter/SQLite.php
- src/Database/Database.php
- tests/e2e/Adapter/Base.php
- Remove inline adapter transactions
- Add abstracted transactions functions to adapter + database
- Wrap CRUD functions in transactions at the database layer
- Allow getting document for update
All of this allows atomic updates. Now when updating a document, we can read the existing document including a `FOR UPDATE` clauses, which will apply a read lock on the row until we complete the update.
Doing this will resolve race conditions where parallel updates overwrite changes.
> Feat atomic updates

- src/Database/Database.php
Fix Deprecated: DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated 
Happens because of reading an empty document
> Return on empty docs 

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Mongo.php
- src/Database/Adapter/Postgres.php
- src/Database/Query.php
- tests/e2e/Adapter/Base.php
This PR fixes issues resulting from nested ID queries as the original references get modified, making subsequent queries fail.
> Fix nested id queries not working

- composer.lock
- docker-compose.yml
- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Mongo.php
- src/Database/Adapter/MySQL.php
- src/Database/Adapter/Postgres.php
- src/Database/Adapter/SQL.php
- src/Database/Adapter/SQLite.php
- src/Database/Database.php
- tests/e2e/Adapter/Base.php
This PR implements the ability to resize string attributes. Currently, it works for MySQL, MariaDB, SQLite, and PostgreSQL. Currently working on fixing it for MongoDB.
> Implement resizing string attributes

- src/Database/Database.php
- tests/e2e/Adapter/Base.php
This PR makes `findOne` return an empty document instead of a false when no document is found. Tests have been updated appropriately.
> Make findOne return empty document instead of false

- src/Database/Database.php
- tests/e2e/Adapter/Base.php
This PR fixes a bug regarding updating relationship attribute names, which occurs because after our method updates the index metadata with the correct data then `updateAttributeMeta` overwrites that with the original data.
To solve this, the index update code has been moved out of updateAttributeMeta; tests have also been added to check these changes solve the `index doesn't exist` bug when double updating relationship names.
> Fix index metadata becoming desynchronised when updating relationship names

- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Mongo.php
- src/Database/Adapter/Postgres.php
- src/Database/Adapter/SQL.php
- src/Database/Adapter/SQLite.php
- src/Database/Database.php
- tests/e2e/Adapter/Base.php
Which is the value in process list
> Get Connection Id

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Postgres.php
- src/Database/Adapter/SQLite.php
- tests/e2e/Adapter/Base.php
- tests/e2e/Adapter/MariaDBTest.php
- tests/e2e/Adapter/MirrorTest.php
- tests/e2e/Adapter/MongoDBTest.php
- tests/e2e/Adapter/MySQLTest.php
- tests/e2e/Adapter/PostgresTest.php
- tests/e2e/Adapter/SQLiteTest.php
- tests/e2e/Adapter/SharedTables/MariaDBTest.php
- tests/e2e/Adapter/SharedTables/MongoDBTest.php
- tests/e2e/Adapter/SharedTables/MySQLTest.php
- tests/e2e/Adapter/SharedTables/PostgresTest.php
- tests/e2e/Adapter/SharedTables/SQLiteTest.php
This PR makes it so that when you deleteAttributes, if the column for the attribute does not exist, the adapter will still return true so the metadata can be cleaned up appropriately. Tests are not included for this as replicating the environment for this isn't easy with the tests architecture we have
> Don't throw on deleteAttribute if column doesn't exist

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/SQLite.php
- tests/e2e/Adapter/Base.php
- tests/e2e/Adapter/MariaDBTest.php
- tests/e2e/Adapter/MirrorTest.php
- tests/e2e/Adapter/MongoDBTest.php
- tests/e2e/Adapter/MySQLTest.php
- tests/e2e/Adapter/PostgresTest.php
- tests/e2e/Adapter/SQLiteTest.php
- tests/e2e/Adapter/SharedTables/MariaDBTest.php
- tests/e2e/Adapter/SharedTables/MongoDBTest.php
- tests/e2e/Adapter/SharedTables/MySQLTest.php
- tests/e2e/Adapter/SharedTables/PostgresTest.php
- tests/e2e/Adapter/SharedTables/SQLiteTest.php
This PR makes it so we can delete indexes that do not exist so we can cleanup metadata, tests have been added to confirm this functionality works as intended.
> Don't throw when deleting indexes that don't exist

- src/Database/Database.php
- src/Database/Mirror.php
- tests/e2e/Adapter/Base.php
This PR makes the bulk document functions return the array of documents that have been modified, tests have been updated accordingly.
> Make bulk methods always return array of documents

- src/Database/Adapter/MariaDB.php
Remove drop table to ensure necessary tables are not accidentally deleted.
> Remove DROP TABLE IF EXISTS

- composer.json
- src/Database/Database.php
- tests/e2e/Adapter/Base.php
Bulk operations didn't previously respect timestamps, this fixes that and adds tests for that case.
> Respect timestamps in bulk operations and add tests

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Postgres.php
- src/Database/Adapter/SQL.php
- src/Database/Validator/Index.php
- tests/e2e/Adapter/Base.php
Reverts utopia-php/database#482
> Revert "Primary key bigint"

- README.md
This PR fixes some mistakes and inconsistencies in the README.
> chore: fixed and improved readme

- composer.lock
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Mongo.php
- src/Database/Adapter/Postgres.php
- src/Database/Database.php
- tests/e2e/Adapter/Base.php
Create documents constructs the column list based on all documents however there is a chance that values don't exist on a document (because of it not being required) meaning it doesn't get set in the bindValues resulting in a diff between the number of values expected and the number of values given.
This PR fixes that by making a column list of all the documents and checking against that when binding values, if a value doesn't exist it will be set as null within the bindValues. Validators from the database adapter should catch if a value is required or doesn't exist at all so we don't need to check that.
Tests have been added to make sure that this fixes the bug explained.
> Fix different column for nulls bug in create documents

- bin/tasks/index.php
- bin/tasks/load.php
- composer.lock
- src/Database/PDO.php
- tests/e2e/Adapter/MariaDBTest.php
- tests/e2e/Adapter/MirrorTest.php
- tests/e2e/Adapter/MySQLTest.php
- tests/e2e/Adapter/PostgresTest.php
- tests/e2e/Adapter/SQLiteTest.php
- tests/e2e/Adapter/SharedTables/MariaDBTest.php
- tests/e2e/Adapter/SharedTables/MySQLTest.php
- tests/e2e/Adapter/SharedTables/PostgresTest.php
- tests/e2e/Adapter/SharedTables/SQLiteTest.php
Add PDO proxy to allow reconnecting with the initial given parameters
> Add PDO proxy

- composer.json
- composer.lock
update to: https://github.com/utopia-php/cache/releases/tag/0.12.0
> chore: bump cache 0.12.*

- src/Database/Database.php
- Prevent starting a transaction if authorization is not permitted.
- Fix array merge , since we use first Cursor/Limit in array of queries
> Move auth outside transaction

- src/Database/Database.php
- src/Database/Mirror.php
- tests/e2e/Adapter/Base.php
Because we accumulate all documents for create/update/upsert/delete documents, we can run into memory issues with large data sets. To mitigate the issue, we change the bulk methods to accept a callback which will fire for each document, instead of returning all documents in an array. Methods will return an integer notifying how many documents were modified - and a callback must be passed to post-process data.
> Feat bulk callbacks

- src/Database/Validator/Query/Filter.php
- tests/e2e/Adapter/Base.php
For blocking queries against attributes against encrypt filters
https://linear.app/appwrite/issue/DAT-440/block-queries-against-encrypted-attributes-with-an-informative-error
> added block queries against encrypt fields

- src/Database/Database.php
- Nothing to skip in updateDocuments.
- @abnegate  Should we skip auth in the find method?
> Skip auth in bulks

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Postgres.php
- src/Database/Database.php
- tests/e2e/Adapter/Base.php
Remove requirement of setting tenant to null before updating system collections
> Remove tenant set on update

- src/Database/Database.php
To ensure single cache entry per null tenant metadata doc
> Allow setting global collections

- src/Database/Database.php
- No authentication is skipped inside the adapter
- We did the same for updateDocuments
> Remove auth skip in deleteDocuments

- src/Database/Database.php
Shared cache key across tenants is great, but ONLY for schema. Doing it for everything also does it for content, and how user A (on project A) and user A (on proejct B) share same cache key.
> Prevent reusing same cache key for multiple documents

- src/Database/Database.php
- tests/e2e/Adapter/Scopes/CollectionTests.php
function setGlobalCollections, that allows you to specify collections that should not include $tenant in their cache key, returned by getCacheKeys
So added tests for this
> added test for global collection test

- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/SQL.php
- src/Database/Database.php
- tests/e2e/Adapter/Scopes/DocumentTests.php
- tests/e2e/Adapter/Scopes/RelationshipTests.php
Because without them:
- It breaks select queries in all statically typed SDKs,
- There are many places we need them internally
- Select queries meant to be for choosing what of your data you want, regardless of internals
- They add <1KB of data, negligible in almost all scenarios
> Re-force internal attribute selection

- src/Database/Database.php
- tests/e2e/Adapter/Scopes/DocumentTests.php
Addresses `PDOException` thrown when documents contain different sets of optional attributes during upsert
> Fix upsert mismatch

- src/Database/Adapter.php
- src/Database/Adapter/MariaDB.php
- src/Database/Adapter/Pool.php
- src/Database/Adapter/Postgres.php
- src/Database/Adapter/SQLite.php
- src/Database/Database.php
- tests/e2e/Adapter/Scopes/SpatialTests.php
Previous -> Spatial attribute should be appended with not null when required toggle which wasn't happening
Current -> updated the altering case for doing it
> updated spatial update attribute

- src/Database/Database.php
- src/Database/Validator/Index.php
- src/Database/Validator/Queries/Documents.php
- src/Database/Validator/Query/Filter.php
- src/Database/Validator/Query/Order.php
- src/Database/Validator/Query/Select.php
- src/Database/Validator/Structure.php
- tests/e2e/Adapter/Scopes/AttributeTests.php
- tests/e2e/Adapter/Scopes/DocumentTests.php
- tests/e2e/Adapter/Scopes/GeneralTests.php
- tests/e2e/Adapter/Scopes/IndexTests.php
Structure Validations were coming for collection attributes along with the internal attributes resulting to structure exceptions for free form document structure in the mongodb adapter
Structure validations happening for the internal attributes only and not for the free form document in the mongodb
Previously due to attributes metadata storage , validations were able to able run and validations were getting done on the each attribute. 
Same for query
For mongodb, the attributes validation are getting skipped -> data directly getting dumped in the underlying db.
For query, we can query on both existing and non existing fields
Same for index
> Add support for schemaless attributes in Database and Structure classes
