utopia-php/database

CONTRIBUTING.md

This PR adds a CONTRIBUTING.md guide which details the PR process and some guidance for creating new adapters.

Feat: Add contributing guide

---

src/Database/Document.php
tests/Database/DocumentTest.php

Added new methods to easily manipulate the Document object.

Feat new doc methods

---

composer.lock
src/Database/Adapter/MariaDB.php
tests/Database/Validator/StructureTest.php

Added transactions support for create, update, and delete document method

Feat MariaDB transactions

---

.travis.yml
Dockerfile

Default Docker version on Travis failed to build. Added manual setup for our extensions.

Fix mongo extension

---

src/Database/Adapter.php
src/Database/Adapter/MariaDB.php
src/Database/Adapter/MongoDB.php
src/Database/Adapter/MySQL.php
tests/Database/Adapter/MariaDBTest.php
tests/Database/Adapter/MongoDBTest.php
tests/Database/Adapter/MySQLTest.php
tests/Database/Base.php

- adds a static value to adapter
- adds exception test for after pagination

feat: static index number for adapter

---

src/Database/Adapter/MariaDB.php
src/Database/Adapter/MongoDB.php
tests/Database/Base.php

- after pagination didn't work when ordering by natural order
- added tests to cover it

fix(order-after): when ordering by natural order

---

src/Database/Validator/Authorization.php
tests/Database/Validator/AuthorizationTest.php

Added a way to skip auth test with a callback

Auth skip method

---

src/Database/Adapter.php
src/Database/Adapter/MariaDB.php
src/Database/Adapter/MongoDB.php
src/Database/Database.php
tests/Database/Base.php

Adds new method to get sum of an attribute

get sum and related tests

---

Dockerfile
README.md
composer.json
composer.lock

This PR splits the single, large compile layer into multiple so compilation can proceed in parallel, rather than sequentially. 
Additionally, this PR bumps some dependency versions and defines PHP8 as the minimum version.
**Testing**
If the build compiles and passes tests, this PR is successful.

Feat: parallel compile builds

---

src/Database/Adapter/MariaDB.php
src/Database/Adapter/MongoDB.php
src/Database/Query.php
src/Database/Validator/Queries.php
src/Database/Validator/QueryValidator.php
tests/Database/Base.php
tests/Database/Validator/QueryValidatorTest.php

This PR will allow Queries to target the `$id` attribute.

Fix: query on $id

---

src/Database/Database.php

This fixes leftover Metadata when an attribute or index wasn't successfully created.
This change basically creates the attribute/index before creating the metadata.

fix: metadata integrity on attributes and indexes

---

composer.lock
src/Database/Validator/OrderAttributes.php
tests/Database/Validator/OrderValidatorTest.php

New validator for order queries to force indexes, similar to queries. This also prevents usage of `_uid`.

Add order attributes validator

---

src/Database/Adapter/MariaDB.php

Takes care of https://github.com/appwrite/appwrite/issues/2906
Edit: tests are on the way

fix: mariadb wrong param bindings to write

---

src/Database/Adapter/MariaDB.php
tests/Database/Base.php

- allow using MariaDB BOOLEAN search keywords and replace them with space
https://github.com/appwrite/appwrite/issues/2394

fix: mariadb search with @ char

---

CONTRIBUTING.md
docs/add-new-adapter.md

- keeping the adding adapter tutorial to separate doc to keep contributing.md short and less overwhelming for new devs

re-organize contributing guidelines

---

src/Database/Database.php
tests/Database/Base.php

Fixes: https://github.com/appwrite/appwrite/issues/3071

respect database nulls while casting

---

.travis.yml
composer.lock
docker-compose.yml
src/Database/Adapter.php
src/Database/Adapter/MariaDB.php
src/Database/Adapter/MongoDB.php
src/Database/Database.php
src/Database/Document.php
src/Database/Validator/OrderAttributes.php
tests/Database/Adapter/MongoDBTest.php
tests/Database/Base.php

- Implemented tests
- Improved PHPDocs
- Added new exceptions

Feat: Improve renameAttribute

---

composer.lock
docker-compose.yml
src/Database/Adapter/MariaDB.php
src/Database/Validator/Structure.php
tests/Database/Adapter/MariaDBTest.php
tests/Database/Adapter/MySQLTest.php

Fix Error:
"Invalid document structure: Attribute "$internalId" has invalid type. Value must be a valid string."
When we use the funtion getDocument:
$document['$internalId'] = $document['_id'];
The value is the autoincrement primary key which is an Integer not a string.

Fix structure validation for creating new attributes in a collection:

---

src/Database/Adapter/MariaDB.php
tests/Database/Base.php

Adding indexes for createdAt , updatedAd + fixes for test

Adding indexes for createdAt , updatedAd + fixes for test

---

composer.lock
src/Database/Adapter/MariaDB.php
tests/Database/Base.php

change last_insert_id() from pdo lastInsertId

---

composer.json
composer.lock
phpbench.json
src/Database/Query.php
src/Database/QueryV1.php
tests/Database/Benchmark/QueryBench.php

Added benchmarks and improved code performance of parser

Feat: Improved performance

---

src/Database/Validator/Permissions.php

- Allow passing list of allowed permission types to permission validator

Refactor permissions update

---

src/Database/Database.php
src/Database/Permission.php

- Add helper for `write` aggregate alias

Feat write helper

---

composer.lock
src/Database/Adapter.php
src/Database/Adapter/MariaDB.php
src/Database/Adapter/Mongo/MongoDBAdapter.php
src/Database/Adapter/MySQL.php
src/Database/Database.php
src/Database/Permission.php
src/Database/Validator/Structure.php
tests/Database/Adapter/MongoDBTest.php
tests/Database/Adapter/MySQLTest.php
tests/Database/Base.php

Add a new Internal attribute in Document _permissions for avoiding subqueries on getting Documents and lists

Create update permissions in document

---

src/Database/Role.php

https://github.com/appwrite/appwrite/pull/3795
https://github.com/appwrite/sdk-generator/pull/546

Add member role helper

---

composer.lock
src/Database/Database.php
tests/Database/Base.php

Fix: updateAttribute for Datetime

---

src/Database/Validator/Authorization.php
tests/Database/Validator/AuthorizationTest.php

- Fixes nested skips resetting status before the callback is completed

Cache and reset to intial auth status in skips

---

README.md
composer.json
composer.lock

https://github.com/appwrite/appwrite/issues/4399#issue-1402869442
I have removed all the mentions of the Authors
. Its issue number 4399 in the main repo. @Meldiron @abnegate

doc-4399-removed_Authors

---

src/Database/Adapter.php
src/Database/Adapter/MariaDB.php
src/Database/Adapter/Mongo/MongoDBAdapter.php
src/Database/Database.php
tests/Database/Base.php

Added `ping` method to test the database and adapter connections.

Added ping method

---

Dockerfile
composer.json
composer.lock

Some of our dependencies are optional and are not needed to use this package.
Also replaces `composer update` with `compsoer update` from Dockerfile.

chore: adjust composer dependencies

---

composer.lock
src/Database/Database.php
src/Database/Validator/Datetime.php
src/Database/Validator/Index.php
src/Database/Validator/Structure.php
tests/Database/Base.php
tests/Database/Validator/DateTimeTest.php

Renaming IndexValidator => Index, IndexValidator.
DatetimeValidator => Datetime

Validators name changes

---

README.md

Updated the build link from `abuse.svg` to `database.svg`

Updated travis ci link in README

---

src/Database/Database.php
tests/Database/Base.php

- Fix many to one parent restrict delete not allowed
- Fix many to many child cascade deleting the parent
Added regression checks

Fix on delete

---

src/Database/Adapter/MariaDB.php
src/Database/Adapter/Postgres.php
src/Database/Adapter/SQL.php
src/Database/Database.php

- Ensure internal attributes are removed when key is set but value is null

Fix no invalid keys

---

composer.lock
src/Database/Adapter/SQL.php
tests/Database/Base.php

Related Issue:
* https://github.com/appwrite/appwrite/issues/6337

Empty fulltext search

---

src/Database/Adapter.php
src/Database/Adapter/MariaDB.php
src/Database/Adapter/Mongo/MongoDBAdapter.php

option to copy internalId when running createDocuments

copy internalId when running createDocuments

---

docker-compose.yml
src/Database/Database.php

+ upgrade MySQL version to 8.033 as well

Delete document before purge

---

src/Database/Validator/Key.php
tests/unit/Validator/KeyTest.php

Related issue:
* https://github.com/appwrite/appwrite/issues/7143

Prevent creating key with empty string

---

src/Database/Adapter/MariaDB.php

Fix usage of deprecated syntax to avoid warnings printed in logs

Fix deprecation warning

---

src/Database/Database.php
tests/e2e/Adapter/Base.php

Remove tenant on Update Attribute

Remove tenant

---

phpunit.xml
src/Database/Database.php
src/Database/Exception/InvalidRelationshipValue.php
src/Database/Validator/Query/Filter.php
tests/e2e/Adapter/Base.php

Update relationships fixes and logic improvement & added more descriptive for error messages.

Invalid values relations update

---

Dockerfile
src/Database/Database.php
src/Database/Validator/Structure.php
tests/e2e/Adapter/Base.php

Custom array is list check didn't catch empty array as a valid list so threw a relationship exception

Fix relationship array check

---

Dockerfile
bin/tasks/index.php
bin/tasks/load.php
bin/tasks/query.php
composer.json
composer.lock
pint.json
src/Database/Adapter.php
src/Database/Adapter/MariaDB.php
src/Database/Adapter/Mongo.php
src/Database/Adapter/Postgres.php
src/Database/Adapter/SQL.php
src/Database/Adapter/SQLite.php
src/Database/Database.php
src/Database/Query.php
src/Database/Validator/Index.php
src/Database/Validator/Queries.php
src/Database/Validator/Query/Filter.php
src/Database/Validator/Structure.php
tests/e2e/Adapter/Base.php
tests/unit/QueryTest.php
tests/unit/Validator/QueryTest.php

A temporary branch for pulling main

Feat framework v2 1

---

composer.lock
src/Database/Adapter/MariaDB.php
tests/e2e/Adapter/Base.php

- Fix update document permissions removals for shared table

Fix permissions Removal

---

.github/workflows/tests.yml
docker-compose.yml
src/Database/Adapter/MariaDB.php
src/Database/Adapter/Postgres.php
src/Database/Adapter/SQLite.php
src/Database/Database.php
tests/e2e/Adapter/Base.php
tests/e2e/Adapter/MariaDBSharedTablesTest.php
tests/e2e/Adapter/MariaDBTest.php
tests/e2e/Adapter/MySQLTest.php
tests/e2e/Adapter/PostgresTest.php
tests/e2e/Adapter/SharedTables/MariaDBTest.php
tests/e2e/Adapter/SharedTables/MongoDBTest.php
tests/e2e/Adapter/SharedTables/MySQLTest.php
tests/e2e/Adapter/SharedTables/PostgresTest.php
tests/e2e/Adapter/SharedTables/SQLiteTest.php

- Add Adapter to tests shared tables

Shared tables tests

---

src/Database/Query.php
tests/unit/QueryTest.php

Fix invalid query contents parse

---

Dockerfile
src/Database/Adapter.php
src/Database/Adapter/MariaDB.php
src/Database/Adapter/Mongo.php
src/Database/Adapter/Postgres.php
src/Database/Database.php
tests/e2e/Adapter/Base.php

- Fix `updatedAt` not updated when incrementing or decrementing an attribute

Fix increment updated

---

src/Database/Adapter/MariaDB.php
src/Database/Adapter/Postgres.php

Fix deadlock caused by selecting permissions for update
https://github.com/user-attachments/assets/e79a39c6-e453-4d89-91e6-0773aea7e411

Fix deadlock when selecting permissions for update

---

phpunit.xml
src/Database/Adapter.php
src/Database/Adapter/MariaDB.php
src/Database/Adapter/Mongo.php
src/Database/Adapter/Postgres.php
src/Database/Adapter/SQLite.php
src/Database/Database.php
tests/e2e/Adapter/Base.php

**Note:** Doesn't support relationships. Is not intended to be used in a public API.

Allow changing document ID

---

src/Database/Database.php
tests/e2e/Adapter/Base.php

Make findOne return empty document instead of false when no matches are found

Update FindOne empty return value

---

composer.lock
src/Database/Database.php

- Remove drop collection 
- Rename adapter before metadata change
- Delete index adapter before metadata change

Remove drop collection try catch

---

src/Database/Database.php
tests/e2e/Adapter/Base.php

- Adds `foreach` method
- Adds new tests for it
- Foreach method will loop through all the documents of the collection that matches the given query

Feat: foreach

---

src/Database/Adapter/MariaDB.php
src/Database/Database.php

Follows same approach as other places that need backwards support for shared tables V1.

Fix: collection deletion on V1
